const BookActionTypes = {
	ININITALIZE: 'BOOK_ININITALIZE',
	CREATE_BOOK: 'BOOK_CREATE_BOOK',
	SELECT_BOOK: 'BOOK_SELECT_BOOK',
	UPDATE_BOOK: 'BOOK_UPDATE_BOOK',
	DELETE_BOOK: 'BOOK_DELETE_BOOK',
	CREATE_SECTION: 'BOOK_CREATE_SECTION',
	SELECT_SECTION: 'BOOK_SELECT_SECTION',
	UPDATE_SECTION: 'BOOK_UPDATE_SECTION',
	DELETE_SECTION: 'BOOK_DELETE_SECTION',
	CREATE_PAGE: 'BOOK_CREATE_PAGE',
	SELECT_PAGE: 'BOOK_SELECT_PAGE',
	UPDATE_PAGE: 'BOOK_UPDATE_PAGE',
	DELETE_PAGE: 'BOOK_DELETE_PAGE'
};

export default BookActionTypes;
